export const queryKeys = {
  mixTankStatus: () => ["mixTankStatus"],
  irrigationTanks: () => ["irrigationTanks"],
  insideCliment: () => ["insideClimentAll"],
  outsideCliment: () => ["outsideCliment"],
  errorCodes: () => ["errorCodes"],
  operatorMode: (zone) => ["operatorMode", zone],
  operatorStatus: (zone) => ["operatorStatus", zone],
  operatorModeEghlim: (zone) => ["operatorModeEghlim", zone],
  foodstuffSchedule: () => ["foodstuffSchedule"],
  foodstuffHistory: (limit) => ["foodstuffHistory", limit],
  foodstuffProgram: (num) => ["foodstuffProgram", num],
  irrigationTanksStatusLogs: () => ["irrigationTanksStatusLogs"],
  irrigationSchedules: () => ["irrigationSchedules"],
  storageIrrigationSchedule: (zone) => ["storageIrrigationSchedule", zone],
  irrigationTanksStatusCalib: () => ["irrigationTanksStatus_calib"],
  payesh: {
    temperaturePart: (zone) => ["payesh", "temperature-part", zone],
    humidityPart: (zone) => ["payesh", "humidity-part", zone],
    temperatureHumidity: (zone) => ["payesh", "temperature-humidity", zone],
  },
  climateRangeStartTime: (zone) => ["climateRangeStartTime", zone],
  climateSpecialParameters: () => ["climateSpecialParameters"],
  climateSettings: (zone, part) => ["climateSettings", zone, part],
  operatorSchedules: (zone) => ["operatorSchedules", zone],
  operatorLogs: (zone) => ["operatorLogs", zone],
  adminConfig: () => ["adminConfig"],
  configAccounts: () => ["configAccounts"],
  solubleEcPhLog: (sensorId) => ["solubleEcPhLog", sensorId],
  solubleEcPhTemperature: () => ["solubleEcPhTemperature"],
  mixTankStatusDetail: () => ["mixTankStatusDetail"],
};
